# Run unit tests using CTest
name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        run: sudo apt-get update && sudo apt-get install -y cmake doxygen
      - name: Build
        run: cmake -DBUILD_DOC=true -DBUILD_TESTS=true -S . -B ./build && cmake --build ./build
      - name: Run tests
        run: cd ./build &&  ctest --output-on-failure -vv ; cd ..
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/html
